spring:
  application:
    name: configuration
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config
  profiles:
    active: native,dev
server:
  port: 8888
  tomcat:
    max-threads: 5